version: '3'

services:

  nginx:
    image: nginx:1-alpine
    ports:
      - 80:80
    depends_on:
      - php
    volumes:
      -  ./docker/etc/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./app:/var/www/

  php:
#    image: php:7.4-fpm
    build:
      context: docker/images/php-fpm
    depends_on:
      - mysql
    volumes:
#      - ./docker/etc/php/php.ini:/usr/local/etc/php/php.ini
      - ./app:/var/www/

  mysql:
    image: mysql:5.7
    volumes:
      - ./docker/data/mysql:/var/lib/mysql
#      - ./docker/mysql/config.cnf:/etc/mysql/conf.d/config.cnf
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}